services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: skeleton
    volumes:
      - './postgres:/var/lib/postgresql/data && chmod -R 077 /var/lib/postgresql/data'
